site_name: "Lars Grit's Portfolio"

theme:
    name: material
    custom_dir: mdocotion/
    sidebar_color: '#f1f5f9'
    logo: assets/logo.svg
    favicon: "assets/new_favicon.ico"
    features:
        - navigation.sections
        - content.tabs.link

plugins:
    - search
    - mermaid2
    - awesome-pages
    - section-index
    - autolinks
    - macros:
          modules: [mkdocs_macros_mdocotion]

markdown_extensions:
    - attr_list
    - md_in_html
    - fenced_code
    - pymdownx.highlight:
          linenums: true
          use_pygments: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

